CREATE TABLE IF NOT EXISTS testing_TEMP(ID int, NAME STRING,PLACE STRING,YEAR STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;

LOAD DATA LOCAL INPATH './data1.txt' INTO TABLE testing_TEMP;

CREATE TABLE IF NOT EXISTS testing_final AS select ID , NAME ,PLACE, "2015"  from testing_TEMP group by ID,NAME,PLACE;

