CREATE TABLE PERSON_PART( ID BIGINT,
		     NAME STRING,
		     ADDRESS STRING,
		     PHONE ARRAY<STRING>,
		     BANKS_BALANCE MAP<STRING,STRING>)
PARTITIONED BY (CITY STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
COLLECTION ITEMS TERMINATED BY ':'
MAP KEYS TERMINATED BY '='
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;
